# Generated by Django 3.0.8 on 2020-07-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
