# Generated by Django 3.0.8 on 2020-07-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200717_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
