# Generated by Django 3.0.8 on 2020-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('preview', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('poster', models.ImageField(null=True, upload_to='course/')),
                ('release_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
