# Generated by Django 3.0.8 on 2020-07-17 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20200717_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(null=True, related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
