# Generated by Django 3.0.8 on 2020-07-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200717_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
